[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = aIYKIHaArode+vt17fsCeqkzZYN0ZG1vZLnviPSXeFM=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer_lab
PublicKey = pQga4RLDZ6m9f3l0Gecq8/P4rfXLjKAf7rn9S1rXA2U=
PresharedKey = s9ZCgXVV5UU6mDFJaZq4pcIBwqdrRhmUc2hElN2X+f0=
AllowedIPs = 10.13.13.2/32

