[Interface]
Address = 10.13.13.2
PrivateKey = oPRIMG6B5apuN13POW/jll56+0X2+RsAO325yux++F8=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = Z2HgKdYH+i/mD9+n4jPz0z08R12KaIyjmtJlpx7lyxo=
PresharedKey = s9ZCgXVV5UU6mDFJaZq4pcIBwqdrRhmUc2hElN2X+f0=
Endpoint = 190.56.173.200:51820
AllowedIPs = 0.0.0.0/0
